name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build and release APK
        run: ./gradlew assembleRelease
      - name: Releasing using Hub
        uses: VladDaniliuk/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          VERSION_VARIABLE: versionName
          APP_FILE: buildSrc/Android.kt
          APP_FOLDER: ./app/release/app.apk
          CHANGELOG_FILE: ./CHANGELOG.md
          RELEASE_TITLE: Automatic release
          NAME_VARIABLE: app-release.apk